### ISSUE TITLE
Fix Yaml file for FBNeo and Arcade

### ISSUE THREAD

**Issue by Ultrahead** [anibaldeboni/screech#21]
The name for Arcade is set as Mame, but since there already is an entry for Mame, it should be replaced to Arcade for correct display of the entry:
  
  - dir: ARCADE
    id: "75"
    name: Arcade

Also, the entry for Final Burn Neo should be also scrapped from MAME:

  - dir: FBNEO
    id: "75"
    name: Final Burn Neo

**Comment by Ultrahead** [comment]
Also for WonderSwan and WSColor it should go:

  - dir: WS
    id: "207"
    name: WonderSwan
  - dir: WSC
    id: "45"
    name: WonderSwan Color

**Comment by Ultrahead** [comment]
In case it helps, this is the way I have the YAML structured:

```
roms: /mnt/SDCARD/Roms/ # Path to the roms folder
logos: /mnt/SDCARD/Emus/_Iconos/Burst! (Centered)
max-scan-depth: 2
ignore-skipped-rom-message: true
exclude-extensions: #
  - ".cue"
  - ".jpg"
  - ".png"
  - ".sub"
  - ".db"
  - ".xml"
  - ".txt"
  - ".dat"
  - ".miyoocmd"
  - ".cfg"
  - ".state"
  - ".srm"
screenscraper:
  username: my_username
  password: my_password
  threads: 3
  media:
    type: mixrbv2
    width: 400
    height: 580
    ignore-missing-region: true
    regions:
      - br
      - us
      - ame
      - wor
      - eu
      - jp
systems:
  - dir: AMSTRAD
    id: "65"
    name: Amstrad - CPC
  - dir: ATOMISWAVE
    id: "53"
    name: Arcades - Atomiswave
  - dir: FBNEO
    id: "75"
    name: Arcades - Final Burn Neo
  - dir: MAME
    id: "75"
    name: Arcades - Mame (Slowest)
  - dir: MAME2003PLUS
    id: "75"
    name: Arcades - Mame 2003
  - dir: MAME2010
    id: "75"
    name: Arcades - Mame 2010
  - dir: PGM
    id: "75"
    name: Arcades - PolyGame Master
  - dir: ATARI800
    id: "43"
    name: Atari - Atari 800
  - dir: ATARI2600
    id: "26"
    name: Atari - Atari 2600
  - dir: ATARI5200
    id: "40"
    name: Atari - Atari 5200
  - dir: ATARI7800
    id: "41"
    name: Atari - Atari 7800
  - dir: JAGUAR
    id: "27"
    name: Atari - Atari Jaguar
  - dir: LYNX
    id: "28"
    name: Atari - Atari Lynx
  - dir: ATARIST
    id: "42"
    name: Atari - Atari ST
  - dir: WS
    id: "207"
    name: Bandai - WonderSwan
  - dir: WSC
    id: "45"
    name: Bandai - WonderSwan Color
  - dir: CPS1
    id: "6"
    name: Capcom - PlaySystem 1
  - dir: CPS2
    id: "7"
    name: Capcom - PlaySystem 2
  - dir: CPS3
    id: "8"
    name: Capcom - PlaySystem 3
  - dir: AMIGA
    id: "64"
    name: Commodore - Amiga
  - dir: AMIGACD
    id: "134"
    name: Commodore - Amiga CD32
  - dir: C64
    id: "66"
    name: Commodore - C64
  - dir: CPLUS4
    id: "99"
    name: Commodore - Plus 4
  - dir: VIC20
    id: "73"
    name: Commodore - VIC 20
  - dir: DOS
    id: "135"
    name: Msft - DOS
  - dir: MSX
    id: "113"
    name: Msft - MSX1
  - dir: MSX2
    id: "116"
    name: Msft - MSX2
  - dir: PC88
    id: "221"
    name: Nec - PC 8000/8800/8801
  - dir: PC98
    id: "208"
    name: Nec - PC 98/9801
  - dir: SFX
    id: "105"
    name: NEC - PC Engine SuperGrafx
  - dir: PCE
    id: "31"
    name: Nec - PC Engine TurboGrafx 16
  - dir: PCECD
    id: "114"
    name: Nec - PC Engine TurboGrafx CD
  - dir: PCFX
    id: "72"
    name: NEC - PC FX
  - dir: NDS
    id: "15"
    name: Nintendo - Nintendo DS
  - dir: FDS
    id: "106"
    name: Nintendo - Famicom Disk System
  - dir: GW
    id: "52"
    name: Nintendo - Game & Watch
  - dir: GB
    id: "9"
    name: Nintendo - GameBoy
  - dir: GBA
    id: "12"
    name: Nintendo - GameBoy Advance
  - dir: GBC
    id: "10"
    name: Nintendo - GameBoy Color
  - dir: N64
    id: "14"
    name: Nintendo - N64
  - dir: N64DD
    id: "122"
    name: Nintendo - N64DD
  - dir: FC
    id: "3"
    name: Nintendo - NES (Famicom)
  - dir: SFC
    id: "4"
    name: Nintendo - SNES
  - dir: SFCMSU
    id: "4"
    name: Nintendo - SNES Hacks
  - dir: VB
    id: "11"
    name: Nintendo - Virtual Boy
  - dir: ARDUBOY
    id: "263"
    name: Other - Arduboy
  - dir: COLECO
    id: "183"
    name: Other - Coleco Vision
  - dir: DAPHNE
    id: "49"
    name: Other - Daphne LaserDisc
  - dir: EASYRPG
    id: "231"
    name: Other - EasyRPG
  - dir: INT
    id: "115"
    name: Other - Mattel Intellivision
  - dir: MEGADUCK
    id: "90"
    name: Other - Megaduck (CougarBoy)
  - dir: OPENBOR
    id: "214"
    name: Other - OpenBOR Engine
  - dir: PALMOS
    id: "219"
    name: Other - Palm (Garnet OS)
  - dir: P3DO
    id: "29"
    name: Other - Panasonic 3DO
  - dir: VIDEOPAC
    id: "104"
    name: Other - Philips Videopac
  - dir: PICO8
    id: "234"
    name: Other - PICO 8
  - dir: SCUMMVM
    id: "123"
    name: Other - SCUMM VM
  - dir: TIC
    id: "222"
    name: Other - TIC 80
  - dir: VECTREX
    id: "102"
    name: Other - Vectrex
  - dir: SUPERVISION
    id: "207"
    name: Other - Watara Supervision
  - dir: NEOGEO
    id: "142"
    name: SNK - NeoGeo AES
  - dir: NEOCD
    id: "70"
    name: SNK - NeoGeo CD
  - dir: NGP
    id: "25"
    name: SNK - NeoGeo Pocket
  - dir: NGC
    id: "82"
    name: SNK - NeoGeo Pocket Color
  - dir: DC
    id: "23"
    name: Sega - Dreamcast
  - dir: GG
    id: "21"
    name: Sega - Game Gear
  - dir: MD
    id: "1"
    name: Sega - Genesis (MegaDrive)
  - dir: MDMSU
    id: "1"
    name: Sega - Genesis (MegaDrive) Hacks
  - dir: MS
    id: "2"
    name: Sega - Master System
  - dir: SG1000
    id: "109"
    name: Sega - SG 1000
  - dir: S32X
    id: "19"
    name: Sega - Sega 32X
  - dir: SCD
    id: "20"
    name: Sega - Sega CD
  - dir: NAOMI
    id: "56"
    name: Sega - Sega Naomi
  - dir: SS
    id: "22"
    name: Sega - Sega Saturn
  - dir: X1
    id: "220"
    name: Sharp - X1
  - dir: X68000
    id: "79"
    name: Sharp - X68000
  - dir: ZX81
    id: "77"
    name: Sinclair - ZX 81
  - dir: ZXSPECTRUM
    id: "76"
    name: Sinclair - ZX Spectrum
  - dir: PS
    id: "57"
    name: Sony - Playstation 1
  - dir: PSP
    id: "61"
    name: Sony - PSP
  - dir: DOOM
    id: ""
    name: X - Doom (do manual scratch)
  - dir: PORTS
    id: ""
    name: X - PortMaster (do manual scratch)
thumbnail:
  width: 400
  height: 580
  dir: /mnt/SDCARD/Imgs/%SYSTEM%/
```
